---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.cache # includes bowers cache
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g codeclimate-test-reporter

install:
  - npm install

script:
  - npm run test
  - npm run build

deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: summerisgone.com
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  upload-dir: bitgo-wallet