---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.cache # includes bowers cache
    - $HOME/.npm

before_install:
  - npm config set spin false
  - npm install -g codeclimate-test-reporter

install:
  - npm install

script:
  - npm run test
